# Generated by Django 3.1.4 on 2023-09-29 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(choices=[('a', 'Начинающий - от 0 до 1 год.'), ('b', 'Средний - от 1 года до 3 лет.'), ('c', 'Профессионал - от 10 лет и выше.')], default='a', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_style', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='archives/')),
                ('performance_experience', models.BooleanField()),
                ('about', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='archives/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musician.city')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musician.experience')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musician.genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_experience', models.BooleanField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musician.city')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musician.genre')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musician.profession')),
            ],
        ),
    ]
